server:
  port: $PORT

eureka:
  instance:
    non-secure-port: 80
    hostname: api-login-all-it.herokuapp.com
  client:
    service-url:
      defaultZone: https://secret-anchorage-03030.herokuapp.com/eureka/
    fetch-registry: true
    register-with-eureka: true


spring:
  encr: ${EPY}
  application:
    name: auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: DATABASE_URL
    username: ${DBUSER}
    password: ${DBPASS}

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: api-login by joao4018
  website: https://www.linkedin.com/in/joao4018/
  github: https://github.com/joao4018

ribbon:
  ReadTimeout: 2147483647
  ConnectTimeout: 2147483647


