server:
  error:
    include-stacktrace: on_param
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/apilogin?&createDatabaseIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false # to turn off a warning while the running

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: api-login by joao4018
  website: https://www.linkedin.com/in/joao4018/
  github: https://github.com/joao4018




