server:
  error:
    include-stacktrace: on_param
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/apilogin?&createDatabaseIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false # to turn off a warning while the running

