server:
  error:
    include-stacktrace: on_param
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apilogin?&createDatabaseIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false # to turn off a warning while the running

